services:
  - type: web
    name: werewolf-online-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
